<?php

namespace project\muridBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * jadwalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class jadwalRepository extends EntityRepository
{
}
