<?php

namespace project\muridBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * pelajaranRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class pelajaranRepository extends EntityRepository
{
}
