<?php

namespace project\adminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DataPendaftaranRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataPendaftaranRepository extends EntityRepository
{
}
